# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Trial.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(756, 694)
        MainWindow.setStyleSheet("background-color:rgb(26, 42, 75)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setGeometry(QtCore.QRect(9, 9, 741, 676))
        self.main_frame.setStyleSheet("background-color: rgb(37, 45, 71);\n"
"border-radius:20px;\n"
"")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.message_area = QtWidgets.QLineEdit(self.main_frame)
        self.message_area.setGeometry(QtCore.QRect(20, 610, 651, 51))
        self.message_area.setStyleSheet("QLineEdit{\n"
"font: 25 14pt \"Bahnschrift Light\";\n"
"color: rgb(112, 128, 140);\n"
"border-style: solid;\n"
"border-width:2px;\n"
"border-color:rgb(112, 128, 140);\n"
"border-radius:20px;\n"
"padding:10px;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border-color:rgb(63, 83, 172);\n"
"background-color:rgb(29, 37, 63);\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"    border-color:rgb(63, 83, 172);\n"
"background-color:rgb(29, 37, 63);\n"
"    color:rgb(63, 83, 172);\n"
"}")
        self.message_area.setObjectName("message_area")
        self.send_button = QtWidgets.QPushButton(self.main_frame)
        self.send_button.setGeometry(QtCore.QRect(680, 610, 51, 51))
        self.send_button.setStyleSheet("QPushButton{\n"
"font: 25 14pt \"Bahnschrift Light\";\n"
"color: rgb(112, 112, 112);\n"
"background-color:rgb(29, 37, 63);\n"
"border:solid 2px;\n"
"border-radius: 25px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border-width:2px;\n"
"    border-color:rgb(63, 83, 172);\n"
"    color:rgb(63, 83, 172);\n"
"}\n"
"\n"
"QPushButton:focus{\n"
"    border-width:2px;\n"
"    border-color:rgb(63, 83, 172);\n"
"    color:rgb(63, 83, 172);\n"
"}")
        self.send_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("paper-plane(1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.send_button.setIcon(icon)
        self.send_button.setIconSize(QtCore.QSize(30, 30))
        self.send_button.setObjectName("send_button")
        self.label = QtWidgets.QLabel(self.main_frame)
        self.label.setGeometry(QtCore.QRect(440, 50, 271, 51))
        self.label.setStyleSheet("QLabel{\n"
"    background-color: rgb(63, 83, 172);\n"
"    font: 25 14pt \"Bahnschrift Light\";\n"
"    color: rgb(112, 128, 140);\n"
"    border-style: solid;\n"
"    border-radius:20px;\n"
"    padding:10px;\n"
"}")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.message_area.setPlaceholderText(_translate("MainWindow", "Type a message"))
        self.label.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
