# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QColor

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(857, 641)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_area = QtWidgets.QTextEdit(self.frame)
        self.main_area.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_area.sizePolicy().hasHeightForWidth())
        self.main_area.setSizePolicy(sizePolicy)
        self.main_area.setStyleSheet("background-color: rgb(39, 40, 34);\n"
"font: 25 12pt \"Bahnschrift Light\";\n"
"color:rgb(248, 248, 242);\n"
"border-radius: 20px;")
        self.main_area.setReadOnly(True)
        self.main_area.setObjectName("main_area")
        self.verticalLayout.addWidget(self.main_area)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.input_area = QtWidgets.QTextEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_area.sizePolicy().hasHeightForWidth())
        self.input_area.setSizePolicy(sizePolicy)
        self.input_area.setStyleSheet("background-color: rgb(117, 113, 94);\n"
"border-radius:10px;\n"
"color:rgb(248, 248, 242);\n"
"font: 25 12pt \"Bahnschrift Light\";")
        self.input_area.setObjectName("input_area")
        self.horizontalLayout.addWidget(self.input_area)
        self.send_btn = QtWidgets.QPushButton(self.frame)
        self.send_btn.setObjectName("send_btn")
        self.horizontalLayout.addWidget(self.send_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.send_btn.clicked.connect(self.clicked)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def clicked(self):

        file = open('C:\\Chat\\lib\\info\\username.txt', 'r')
        data = file.read()
        data = data.rstrip('\n')        
        self.main_area.setTextColor(QColor(249, 38, 114))
        self.main_area.setFontPointSize(10)
        self.main_area.append(data)
        
        self.main_area.setFontPointSize(12)
        self.main_area.setTextColor(QColor(248, 248, 242))
        dta = self.input_area.toPlainText()
        dta = dta.rstrip('\n')
        self.main_area.append(dta)
        self.input_area.setText('')


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.input_area.setPlaceholderText(_translate("MainWindow", "Type a message"))
        self.send_btn.setText(_translate("MainWindow", "Send"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
